export const MenuList = [
  {
    id: 0,
    title: 'Veg Burger',
    price: '45',
    imageUrl: require('../img/strawberry.png'),
    category: 'burger',
  },
  {
    id: 1,
    title: 'Corn Burger',
    price: '50',
    category: 'burger',
    imageUrl: require('../img/chicken.png'),
  },
  {
    id: 2,
    title: 'Nachos Burger',
    price: '80',
    category: 'burger',
    imageUrl: require('../img/fish.png'),
  },
  {
    id: 3,
    title: 'Cheese Burger',
    price: '80',
    category: 'burger',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 4,
    title: 'Crunchy Panner Burger',
    price: '100',
    category: 'burger',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 5,
    title: 'Rosted Panner Burger',
    price: '110',
    category: 'burger',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 6,
    title: 'King Special Burger',
    price: '120',
    category: 'burger',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 7,
    title: 'Chicken Burger',
    price: '70',
    category: 'burger',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 8,
    title: 'Spicy Chicken Burger',
    price: '80',
    category: 'burger',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 9,
    title: 'Egg Burger',
    price: '70',
    category: 'burger',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 10,
    title: 'Cheesy Egg Burger',
    price: '90',
    category: 'burger',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 11,
    title: 'Fish Burger',
    price: '110',
    category: 'burger',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 12,
    title: 'Roasted Chicken Burger',
    price: '120',
    category: 'burger',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 13,
    title: "King's Special Non-Veg Burger",
    price: '130',
    category: 'burger',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 14,
    title: 'Veg Sandwich',
    price: '80',
    category: 'sandwich',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 15,
    title: 'Mexican Corn Sandwich',
    price: '100',
    category: 'sandwich',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 16,
    title: 'Cheese Mozzarella Sandwich',
    price: '100',
    category: 'sandwich',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 17,
    title: 'Cheese Corn Sandwich',
    price: '120',
    category: 'sandwich',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 18,
    title: 'Spicy Panner Sandwich',
    price: '120',
    category: 'sandwich',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 19,
    title: 'Roasted Panner Sandwich',
    price: '120',
    category: 'sandwich',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 20,
    title: "King's Special Sandwich ",
    price: '130',
    category: 'sandwich',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 21,
    title: 'Chicken Sandwich',
    price: '100',
    category: 'sandwich',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 22,
    title: 'Chicken Corn Sandwich',
    price: '110',
    category: 'sandwich',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 23,
    title: 'Cripsy Chicken Sandwich',
    price: '120',
    category: 'sandwich',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 24,
    title: "King's Special Non-Veg Sandwich ",
    price: '130',
    category: 'sandwich',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 25,
    title: 'Red Sauce Pasta',
    price: '130',
    category: 'pasta',
    imageUrl: require('../img/chicken.png'),
  },
  {
    id: 26,
    title: 'White Sauce Pasta',
    price: '130',
    category: 'pasta',
    imageUrl: require('../img/chicken.png'),
  },
  {
    id: 27,
    title: 'Mix Pasta',
    price: '140',
    category: 'pasta',
    imageUrl: require('../img/chicken.png'),
  },
  {
    id: 28,
    title: 'Tandoori Pasta',
    price: '150',
    category: 'pasta',
    imageUrl: require('../img/chicken.png'),
  },
  {
    id: 29,
    title: 'Loaded Fries Jar',
    price: '150',
    category: 'fries-jar',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 30,
    title: 'Perry Fries Jar',
    price: '150',
    category: 'fries-jar',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 31,
    title: 'Spicy Fries Jar',
    price: '160',
    category: 'fries-jar',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 32,
    title: 'Spicy Masala Fries Jar',
    price: '160',
    category: 'fries-jar',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 33,
    title: 'Crincle Fries Jar',
    price: '160',
    category: 'fries-jar',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 34,
    title: 'Panner Pop Fries Jar',
    price: '170',
    category: 'fries-jar',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 35,
    title: 'Chicken Pop Jar',
    price: '170',
    category: 'fries-jar',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 36,
    title: 'Tandoori Chicken Jar',
    price: '180',
    category: 'fries-jar',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 37,
    title: 'Crincle Non-Veg Jar',
    price: '180',
    category: 'fries-jar',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 38,
    title: 'Cheesy Chicken Jar',
    price: '180',
    category: 'fries-jar',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 39,
    title: 'Perry Jar',
    price: '180',
    category: 'fries-jar',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 40,
    title: 'Veg Wrap',
    price: '120',
    category: 'wraps',
    imageUrl: require('../img/fish.png'),
  },
  {
    id: 41,
    title: 'Crispy Panner Wrap',
    price: '140',
    category: 'wraps',
    imageUrl: require('../img/fish.png'),
  },
  {
    id: 42,
    title: 'Cheese Corn Wrap',
    price: '140',
    category: 'wraps',
    imageUrl: require('../img/fish.png'),
  },
  {
    id: 43,
    title: 'Spicky Strips Wrap',
    price: '140',
    category: 'wraps',
    imageUrl: require('../img/fish.png'),
  },
  {
    id: 44,
    title: 'Roasted Panner Wrap',
    price: '150',
    category: 'wraps',
    imageUrl: require('../img/fish.png'),
  },
  {
    id: 45,
    title: "King's Special Wrap",
    price: '160',
    category: 'wraps',
    imageUrl: require('../img/fish.png'),
  },
  {
    id: 46,
    title: 'Crispy Chicken Wrap',
    price: '170',
    category: 'wraps',
    imageUrl: require('../img/fish.png'),
  },
  {
    id: 47,
    title: 'Chicken Butter Wrap',
    price: '170',
    category: 'wraps',
    imageUrl: require('../img/fish.png'),
  },
  {
    id: 48,
    title: 'Roasted Chicken Wrap',
    price: '180',
    category: 'wraps',
    imageUrl: require('../img/fish.png'),
  },
  {
    id: 49,
    title: "King's Chicken Wrap",
    price: '190',
    category: 'wraps',
    imageUrl: require('../img/fish.png'),
  },
  {
    id: 50,
    title: 'Mojito Mint',
    price: '90',
    category: 'refreshers',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 51,
    title: 'Bubble Gum',
    price: '90',
    category: 'refreshers',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 52,
    title: 'Green Apple',
    price: '90',
    category: 'refreshers',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 53,
    title: 'Blue Cracho',
    price: '90',
    category: 'refreshers',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 54,
    title: 'Spicy Mango',
    price: '90',
    category: 'refreshers',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 55,
    title: 'Chilly Guava',
    price: '90',
    category: 'refreshers',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 60,
    title: "King's Electrlly",
    price: '100',
    category: 'refreshers',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 61,
    title: 'Veg Pop Salad',
    price: '140',
    category: 'salad',
    imageUrl: require('../img/chicken.png'),
  },
  {
    id: 62,
    title: 'Veg Strips Salad',
    price: '150',
    category: 'salad',
    imageUrl: require('../img/chicken.png'),
  },
  {
    id: 63,
    title: 'Nachos Salad',
    price: '150',
    category: 'salad',
    imageUrl: require('../img/chicken.png'),
  },
  {
    id: 64,
    title: 'Cheesy Corn Salad',
    price: '170',
    category: 'salad',
    imageUrl: require('../img/chicken.png'),
  },
  {
    id: 65,
    title: 'Crispy Chicken Salad',
    price: '180',
    category: 'salad',
    imageUrl: require('../img/chicken.png'),
  },
  {
    id: 66,
    title: 'Roasted Chicken Salad',
    price: '190',
    category: 'salad',
    imageUrl: require('../img/chicken.png'),
  },
  {
    id: 67,
    title: "King's Chicken Salad",
    price: '200',
    category: 'salad',
    imageUrl: require('../img/chicken.png'),
  },
  {
    id: 68,
    title: 'Vanilla Shake',
    price: '120',
    category: 'shakes',
    imageUrl: require('../img/chicken.png'),
  },
  {
    id: 69,
    title: 'Strawberry Shake',
    price: '130',
    category: 'shakes',
    imageUrl: require('../img/strawberry.png'),
  },
  {
    id: 701,
    title: 'Butter Scotch Shake',
    price: '130',
    category: 'shakes',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 70,
    title: 'Chocklate Shake',
    price: '130',
    category: 'shakes',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 71,
    title: 'Oreo Shake',
    price: '130',
    category: 'shakes',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 72,
    title: 'Banana Caramal Shake',
    price: '130',
    category: 'shakes',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 73,
    title: 'Pineapple Shake',
    price: '130',
    category: 'shakes',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 74,
    title: 'Black Current Shake',
    price: '130',
    category: 'shakes',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 75,
    title: 'Bubble Gum Shake',
    price: '130',
    category: 'shakes',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 76,
    title: 'Kitkat Shake',
    price: '140',
    category: 'shakes',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 77,
    title: 'Oreo Cold Coffee',
    price: '140',
    category: 'shakes',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 78,
    title: 'French Fries',
    price: '80',
    category: 'fries',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 79,
    title: 'Perry Fries',
    price: '100',
    category: 'fries',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 80,
    title: 'Masala Fries',
    price: '120',
    category: 'fries',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 81,
    title: 'Krinkle Fries',
    price: '120',
    category: 'fries',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 82,
    title: 'Perry Krinkle Fries',
    price: '130',
    category: 'fries',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 83,
    title: 'Veg Pops (12 pcs)',
    price: '90',
    category: 'snaks',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 84,
    title: 'Veg Strips (6 pcs)',
    price: '90',
    category: 'snaks',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 85,
    title: 'Panner Pops (10 pcs)',
    price: '150',
    category: 'snaks',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 86,
    title: 'Panner Strips (6pcs)',
    price: '130',
    category: 'snaks',
    imageUrl: require('../img/icecream.png'),
  },
  {
    id: 87,
    title: 'Cheese Corn Strips (6 pcs)',
    price: '170',
    category: 'snaks',
    imageUrl: require('../img/icecream.png'),
  },
];
